### ISSUE TITLE
unable to apply patch v137/atmosphere

### ISSUE THREAD

**Issue by yrrrlove** [ooa113y/umineko-catbox-english#1] opened 2021-07-21 18:51 UTC
i've attempted to patch umineko v1.0 and v1.0.3 without success. after following instructions and merging the patch with my atmosphere folder, the game is still unfortunately in japanese. is there something i'm missing?

thanks for your hard work!

**Comment by ooa113y** [comment] 2021-07-21 19:10
I haven't actually tested this on a real Switch, so I'm not sure of the issue. However, I have an idea of what the cause might be. Can you test v138 once it finishes building?

**Comment by yrrrlove** [comment] 2021-07-21 19:22
beautiful! works perfectly now - thanks for the super quickfix!

**Comment by ooa113y** [comment] 2021-07-21 19:22
Awesome! Closing this as it's fixed via 2bee8a4.

**Closed by ooa113y** 2021-07-21 19:22 UTC
